site_name: 802.11&wlan&wi-fi学习资料

nav:
    - 网站简介: index.md
    - 关于作者: about.md
    - 资料汇总: wlan_all_materials.md
theme:
    name: material
    palette:
        # Palette toggle for light mode
        - scheme: default
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to light mode
    palette:
        primary: green
        accent: deep orange
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.arithmatex:
        generic: true
    # images
    - attr_list
    - md_in_html

extra:
    social:
        - icon: fontawesome/solid/paper-plane
          link: mailto:448778313@qq.com
    generator: false


extra_css:
    - stylesheets/extra.css

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2023 - 2023 w512
